# example
stages:
  - name: Build and Push
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: nginx:${CICD_EXECUTION_SEQUENCE}
          # Optionally push to remote registry
          pushRemote: true
  - name: Deploy some workloads
    steps:
      - applyYamlConfig:
          path: ./deploy/deployment.yaml