# example
stages:
  - name: Build something
    # Conditions for stages
    # Multiple steps run concurrently
    steps:
      - runScriptConfig:
          image: busybox
          shellScript: echo ${FIRST_KEY} && echo ${ALIAS_ENV}
        # Set environment variables in container for the step
        env:
          FIRST_KEY: VALUE
          SECOND_KEY: VALUE2
        # Set environment variables from project secrets
        envFrom:
          - sourceName: my-secret
            sourceKey: secret-key
            targetKey: ALIAS_ENV
      - runScriptConfig:
          image: busybox
          shellScript: date -R
        # Conditions for steps
        when:
          branch: [ master, dev ]
          event: push
  - name: Publish my image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          # Optionally push to remote registry
          pushRemote: true
          registry: reg.example.com
  - name: Deploy some workloads
    steps:
      - applyYamlConfig:
          path: ./deploy/deployment.yaml